print("문자 선택 연산자에 대해 알아볼까요?")
print("안녕하세요"[0])
print("안녕하세요"[1])
print("안녕하세요"[2])
print("안녕하세요"[3])
print("안녕하세요"[4])
print()
print("문자를 뒤에서부터 선택해 볼까요?")
print("안녕하세요"[-1])
print("안녕하세요"[-2])
print("안녕하세요"[-3])
print("안녕하세요"[-4])
print("안녕하세요"[-5])
print()
print("안녕하세요"[1:4])
print("안녕하세요"[0:2])
print("안녕하세요"[1:3])
print("안녕하세요"[:4])
print("안녕하세요"[4:])
print()
hello = "안녕하세요"
print(hello[0:2])
print()
print()
print(len("안녕하세요"))
print()

print()
print("7//5=", 7//5)
print()
print("7%5=", 7%5)

print("2**4=", 2**4)
print()
print(2+2-2*2/2*2)
print(2-2+2/2*2+2)
str = "문자열"
num = "1004"
print(str + num)
